### ISSUE TITLE
cert field valid_before still cannot be assign with "forever" on 0.9.2

### ISSUE THREAD

**Issue by gzm55** [scheiblingco/sshkey-tools#28]
when pass "forever" to valid_before field for signing, we met two issues:

1. `DATA_TYPE` of ValidAfterField and ValidBeforeField are still without 'str' type
2. `__validate_value__()` of ValidBeforeField and DateTimeField blocks the "forever" value

**Comment by scheibling** [comment]
I'm likely only going to change the ValidBefore field, since setting the ValidAfter field to forever would render the certificate useless until 19th of January 2038, probably after as well

**Comment by gzm55** [comment]
yes, ValidBefore should accept "forever", and ValidAfter should accept "always" (which is mapping to 0)

**Comment by scheibling** [comment]
For practical reasons I've mapped "always" to 1, but apart from that everything will be resolved in 0.10.1 with #32

**Comment by gzm55** [comment]
0.10.1 works, thanks!
