### ISSUE TITLE
incompatible with cryptography>=41.0.0

### ISSUE THREAD

**Issue by gzm55** [scheiblingco/sshkey-tools#29]
cryptography 41.0 seems introduce some breaking changes

**Comment by scheibling** [comment]
Is that related to the deprecation of DSA? Or anything else apart from that?

Haven't had a chance to look closer at it yet, I'll do that during the weekend

**Comment by gzm55** [comment]
yes, i met an error about DSA import, then rollback to 40.0 version

**Comment by scheibling** [comment]
I'll have a look at that today, thanks for the notice

**Comment by scheibling** [comment]
For now, I've locked the dependency for 0.9.3+-versions to cryptography<41, then remove the DSA support in 0.10 to be able to follow newer releases of cryptography

**Comment by scheibling** [comment]
DSA support removed with #31, will be released with 0.10.1

**Comment by gzm55** [comment]
@scheibling the requirements.txt should limit the cryptography version after 0.10.1

```pip
cryptography>=41.0
```

**Comment by scheibling** [comment]
Sorry for the late reply, this is fixed by #34 and will be out with 0.10.2 in a couple of minutes
