### ISSUE TITLE
Bug: Error importing "sshkey_tools.keys" (Module 'openssl' has no attribute 'ed25519')

### ISSUE THREAD

**Issue by andresalvcar** [scheiblingco/sshkey-tools#33]
Error importing:

from sshkey_tools.keys import (
    RsaPrivateKey,
    EcdsaPrivateKey,
    Ed25519PrivateKey,
    EcdsaCurves
)

AttributeError: module 'openssl' has no attribute 'ed25519'

Few days ago, it worked perfectly fine. Now I am not able to work with this library. I tried to uninstall, update and go back older versions, didn't work.

**Comment by scheibling** [comment]
Let me check this, the Cryptography library recently made some changes to their structure which caused some issues a while back. 
Which Python version are you currently using?

**Comment by scheibling** [comment]
Strange, tried it in a fresh environment now and it seems to work, but there could be a version conflict somewhere. Would you mind trying this?

1. Grab a copy of the repo, install the packages from requirements-test.txt and run ```python3 -m unittest discover tests/``` to run through the tests to see if they succeed or if they fail as well
2. Get a list of python packages and versions in use in the virtual environment (or other environment you're running in) and paste it here

**Comment by scheibling** [comment]
Hi, nevermind the last comment. I was able to reproduce this with the Cryptography version at <41, looks like I forgot to add that constraint to the requirements when I updated the code for the newer versions. You could try manually upgrading that library by running ```pip3 install --upgrade "cryptography>=41.0"```

**Comment by andresalvcar** [comment]
Hello @scheibling . I have followed the steps and now I don't have any problem with the library. Thank you very much!

**Comment by scheibling** [comment]
Fantastic, thank you for the feedback! I'll send out 0.10.2 (#34) in a little bit which has the minimum versions specified, you shouldn't need to run into this in the future
